### PR TITLE
Commit ClickGUI/ArrayList Updates

### PR DESCRIPTION
**Pull request by AcaiBerii**
Delicious ZeroDay b21 colored ClickGUI

Content contained in issue #85  
committed this bc oxidewavelength said so :)))

### CODE REVIEW

**Comment by josephworks** [comment]
There is no chance this is going to be accepted at its current state:
image
You arent supposed to push the Minecraft source.

**Comment by OxideWaveLength** [comment]
I did notice there were a bit too many files, as Joseph pointed out.
I'm not sure why this could be, but I think a way of fixing it would be to delete this PR and the fork, then re-fork again, add "minecraft/net" to the gitignore and commit. Then add your changes to the client, commit again and remove "minecraft/net" from the gitignore.
Unless you have also made changes to Minecraft's source for the Gui

**Comment by AcaiBerii** [comment]
> I did notice there were a bit too many files, as Joseph pointed out.
> I'm not sure why this could be, but I think a way of fixing it would be to delete this PR and the fork, then re-fork again, add "minecraft/net" to the gitignore and commit. Then add your changes to the client, commit again and remove "minecraft/net" from the gitignore.
> Unless you have also made changes to Minecraft's source for the Gui

I have made changes to Minecraft's source for the Gui by making it extend EventListener.

**Comment by josephworks** [comment]
If you saw my deleted comment, I deleted it cause it was it was poorly worded and aggressive. 
however, I read over the commit changes and realized that there were simply way too many files added besides just a GUI, which didn’t match with the PR description.
It would probably be easier to fix this issue with a software like gitkraken, this would be very difficult to do with GitHub desktop.

**Comment by AcaiBerii** [comment]
> If you saw my deleted comment, I deleted it cause it was it was poorly worded and aggressive.
> however, I read over the commit changes and realized that there were simply way too many files added besides just a GUI, which didn’t match with the PR description.
> It would probably be easier to fix this issue with a software like gitkraken, this would be very difficult to do with GitHub desktop.

I'm now using SourceTree.

Should I still use GitKraken though? I've used it before, not a fan.

**Comment by josephworks** [comment]
I personally use it and it's pretty nice. I've never used sourcetree.

**Pull request closed without merging**
