### PR TITLE
Fix for XRay in other languages.

### PR DESCRIPTION
**Pull request by ZeProf2Code**
The XRay exception list was working with the language who is bad because if you change your language, you will need to add all the exceptions again in that language.
Now, it takes the English localized name whatever your language is.

### CODE REVIEW

**Comment by OxideWaveLength** [comment]
Welcome and thank you for your PR!
The issue is present, but the method I18n#translateToFallback doesn't seem to exist in this version. Is there an alternative to that built-in for Minecraft 1.8.9? Or does the en_US locale need to be loaded manually?
I hope to hear back from you soon! Thanks for spotting this one

**Comment by ZeProf2Code** [comment]
Oh sorry, I'm using 1.12.2, I will maybe look later if I found another method.

**Comment by OxideWaveLength** [comment]
No worries! I think the English locale needs to be loaded manually in 1.8.9
I will look into it when I have some time

**Comment by OxideWaveLength** [comment]
Quoting the commit message,
> I will merge the PR tomorrow if no issue comes up before then
Thanks again for opening the PR!

**Pull request merged**
